### ISSUE TITLE
Docs Website is Down

### ISSUE THREAD

**Issue by Akshay-akkay** [paxengine/pax#179]

**Comment by zackbrown** [comment]
Thanks for reporting this — I'm guessing you found a link to an older domain somewhere; do you remember where you found the broken link?

The docs can be found at https://docs.pax.dev/

**Comment by eliot-akira** [comment]
Maybe related to this issue, I found a broken link in the repository [`paxengine/docs`](https://github.com/paxengine/docs), not in the files but in the repo description setting.

![paxengine-docs-repo-about](https://github.com/user-attachments/assets/ca5730be-b9ae-4044-a7f8-3eebdff31a67)

The domain `pax-lang.org` doesn't go anywhere. It can be edited via the settings icon, Edit repository details ->  Website.

Searching for this domain in the org repos, there's one match.

https://github.com/search?q=org%3Apaxengine+pax-lang.org&type=code

![paxengine-pax-pax-lang-org](https://github.com/user-attachments/assets/4bbc984a-6163-408e-8e35-e7971775ffa6)

**Comment by zackbrown** [comment]
Thank you for your help, @eliot-akira !  I've updated the GH link 
<img width="375" alt="image" src="https://github.com/user-attachments/assets/eebe3777-996e-40f8-b55d-2095204b20a4">

Marking this issue as resolved.
